/*
 * the Mock file instead of network data.
 */
import { IndexData } from '../IndexData';
export { IndexDataList }

const IndexDataList: IndexData[] = [
  new IndexData('1', "排行榜", "pages/RankPage"),
  new IndexData('2', "", ""),
  new IndexData('3', "", ""),
  new IndexData('4', "", ""),
  new IndexData('5', "", ""),
  new IndexData('6', "", ""),
  new IndexData('7', "", ""),
  new IndexData('8', "", ""),
];
