/*
 * the Mock file instead of network data.
 */
import { RankData } from '../RankData';
export { RankDataList1, RankDataList2}

const RankDataList1: RankData[] = [
  new RankData('1', "草莓", "2000"),
  new RankData('2', "黑莓", "1200"),
  new RankData('3', "蓝莓", "400"),
  new RankData('4', "西瓜", "389"),
  new RankData('5', "苹果", "300"),
  new RankData('6', "香蕉", "239"),
  new RankData('7', "哈密瓜", "200"),
  new RankData('8', "香瓜", "100"),
];

const RankDataList2: RankData[] = [
  new RankData('1', "华为", "2000"),
  new RankData('2', "小米", "1200"),
  new RankData('3', "理想", "400"),
  new RankData('4', "特斯拉", "389"),
  new RankData('5', "小鹏", "300"),
  new RankData('6', "蔚来", "239"),
];


